services:
  aua-poker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aua-poker-app
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONPATH: /app/src
    working_dir: /app
    command: ["python", "main.py"]
    volumes:
      - .:/app
    mem_limit: 256m
    cpus: 0.50
