services:
  aua-poker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aua-poker-app
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONPATH: /app/src
    working_dir: /app
    command:
      [
        "sh",
        "-c",
        "python main.py && uvicorn app:app --host 0.0.0.0 --port 8000",
      ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    mem_limit: 256m
    cpus: 0.50
